# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 12:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Polity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('polity_type', models.CharField(choices=[('country', 'Country'), ('province', 'Province'), ('city', 'City'), ('town', 'Town'), ('hamlet', 'Hamlet'), ('regional', 'Regional Municipality')], default='City', max_length=50)),
                ('web_site', models.URLField(blank=True, null=True)),
                ('election_website', models.URLField(blank=True, null=True)),
                ('next_election', models.DateField(blank=True, null=True)),
                ('num_representatives', models.IntegerField(blank=True, null=True)),
                ('num_wards', models.IntegerField(blank=True, null=True)),
                ('separate_executive', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polity', to=settings.AUTH_USER_MODEL)),
                ('parent_polity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='explorer.Polity')),
            ],
        ),
    ]
