# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0002_auto_20170608_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='polity',
            name='polity_type',
            field=models.CharField(choices=[('country', 'Country'), ('province', 'Province'), ('city', 'City'), ('town', 'Town'), ('hamlet', 'Hamlet'), ('regional', 'Regional Municipality')], default='City', max_length=50),
        ),
    ]
