# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0002_auto_20170623_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement', models.IntegerField(default=5)),
                ('importance', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incumbent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(blank=True, max_length=25, null=True)),
                ('num_reps', models.IntegerField(default=1)),
                ('is_whole_polity', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_date', models.DateField()),
                ('start_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Politician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('web_site', models.URLField(blank=True, null=True)),
                ('twitter_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=100)),
                ('election', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='explorer.Election')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('poll', models.ManyToManyField(to='explorer.Poll')),
            ],
        ),
        migrations.RemoveField(
            model_name='polity',
            name='creator',
        ),
        migrations.CreateModel(
            name='CandidatePosition',
            fields=[
                ('answer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='explorer.Answer')),
            ],
            bases=('explorer.answer',),
        ),
        migrations.CreateModel(
            name='PublicAnswer',
            fields=[
                ('answer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='explorer.Answer')),
                ('ip_address', models.GenericIPAddressField()),
                ('session_id', models.CharField(max_length=255)),
            ],
            bases=('explorer.answer',),
        ),
        migrations.AddField(
            model_name='election',
            name='polity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorer.Polity'),
        ),
        migrations.AddField(
            model_name='district',
            name='polity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorer.Polity'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorer.District'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorer.Election'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='politician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorer.Politician'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorer.Question'),
        ),
        migrations.AddField(
            model_name='candidateposition',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorer.Candidate'),
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together=set([('politician', 'election', 'district')]),
        ),
    ]
