# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0003_auto_20170625_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='shapefile_link',
            field=models.URLField(default='www.google.ca'),
            preserve_default=False,
        ),
    ]
