# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0003_polity_polity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polity',
            name='election_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='polity',
            name='next_election',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='polity',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='polity',
            name='num_representatives',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='polity',
            name='num_wards',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='polity',
            name='parent_polity',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='explorer.Polity'),
        ),
        migrations.AlterField(
            model_name='polity',
            name='separate_executive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='polity',
            name='web_site',
            field=models.URLField(blank=True, null=True),
        ),
    ]
