# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0004_auto_20170609_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polity',
            name='parent_polity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='explorer.Polity'),
        ),
    ]
