# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0005_auto_20170625_0617'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incumbent', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='district',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='election',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='politician',
        ),
        migrations.AlterField(
            model_name='candidateposition',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorer.ElectionCandidate'),
        ),
        migrations.AlterField(
            model_name='district',
            name='polity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='explorer.Polity'),
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
        migrations.AddField(
            model_name='electioncandidate',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorer.District'),
        ),
        migrations.AddField(
            model_name='electioncandidate',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorer.Election'),
        ),
        migrations.AddField(
            model_name='electioncandidate',
            name='politician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_in', to='explorer.Politician'),
        ),
        migrations.AlterUniqueTogether(
            name='electioncandidate',
            unique_together=set([('politician', 'election', 'district')]),
        ),
    ]
