# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0006_auto_20170626_0345'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Politician',
            new_name='Candidate',
        ),
        migrations.RenameField(
            model_name='election',
            old_name='start_date',
            new_name='campaign_start_date',
        ),
        migrations.RenameField(
            model_name='electioncandidate',
            old_name='politician',
            new_name='candidate',
        ),
        migrations.AlterField(
            model_name='electioncandidate',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_details', to='explorer.Election'),
        ),
        migrations.AlterUniqueTogether(
            name='electioncandidate',
            unique_together=set([('candidate', 'election', 'district')]),
        ),
    ]
