# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0009_auto_20170627_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateposition',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='explorer.ElectionCandidate'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ManyToManyField(related_name='category_questions', to='explorer.IssueCategory'),
        ),
    ]
